---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

## Tibbles

- `str_standardize()` takes a table and return standardized variable names (ie remove blank spaces and replace them with "_")
- `set_standard_names()`takes a table and return a table with standardized variable names

```{r}
library(readxl)
library(dplyr)
library(plyr)
library(tricky)
#download.file(
#  url = "http://www.data.gouv.fr/fr/datasets/panorama-des-grands-projets-si-de-letat-1/", 
#  destfile = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx"
#  )

read_excel(path = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx") %>%   glimpse()
```

```{r}
read_excel(
  path = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx"
  ) %>% 
  setNames(str_standardize(.)) %>%
  glimpse()
```


```{r}
read_excel(
  path = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx"
  ) %>% 
  set_standard_names() %>%
  glimpse()
```

## Missing values

* `count_na()` returns a table of missing and non-missing values in a vector

```{r}
read_excel(path = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx") %>% 
  set_standard_names() %>% 
  .$ministere_porteur %>% 
  count_na()
```

```{r}
read_excel(path = "raw-data/DINSIC-Panorama_des_grands_projets_SI_20161116.xlsx") %>% 
  ldply(.data = ., .fun = count_na, .id = "variable") %>% 
  group_by(variable) %>% 
  mutate(share = n / sum(n)) %>% 
  filter(missing == TRUE) %>% 
  select(variable, n_missing = n, share_missing = share)
```

```{r}
plyr::ldply(.data = table_training, .fun = count_na)

```

